# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c3ea0eea226c185da821c6665cd89d0dd7f2a34d1bc732c27d53f9e290c2b32455eb94e55c111a23c24760209700a78096d545f6420c637fb6c7233a78aca0

test:
  secret_key_base: 5336618c1f84976ae2f3d0f56764d86327b0a1c6e3f57aff27b650fe4fac8c56530d8181e4465133e531b3c8bd13593c4f3d8b080e8c143fd5590b1d09943271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
